# Generated by Django 5.2.4 on 2025-07-28 10:36

import django.db.models.deletion
import safe_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_number', models.CharField(max_length=30, unique=True)),
                ('user_id', models.CharField(max_length=30)),
                ('vehicle_id', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('pickup_location', models.CharField(max_length=30)),
                ('dropoff_location', models.CharField(max_length=30)),
                ('driver_choice', models.CharField(default='self_drive', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact_form_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name_page', models.TextField(max_length=30)),
                ('contact_email', models.EmailField(max_length=50)),
                ('messege', models.TextField()),
                ('if_username', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('Location_image', models.ImageField(blank=True, null=True, upload_to=safe_admin.models.user_city_image_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Marketing_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_profile_image', models.ImageField(blank=True, null=True, upload_to=safe_admin.models.user_profile_image_upload_path)),
                ('user_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('driver_license_number', models.CharField(max_length=255)),
                ('addhar_number', models.CharField(max_length=255)),
                ('user_addhar_image', models.ImageField(upload_to=safe_admin.models.user_addhar_image_upload_path)),
                ('user_dl_image', models.ImageField(upload_to=safe_admin.models.user_dl_image_upload_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=safe_admin.models.user_staff_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('area_forigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.location')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to=safe_admin.models.vehicle_image_upload_path)),
                ('hourly_rate_wo_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate_with_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rate_wo_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rate_with_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_rate_wo_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_rate_with_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fif_day_rate_wo_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fif_day_rate_with_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_rate_wo_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_rate_with_driver', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], max_length=20)),
                ('allot_city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.vehiclecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_of_origin', models.TextField(max_length=300)),
                ('picl_drop', models.CharField(choices=[('pickup', 'pickup'), ('drop', 'drop')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pickup_drop_bookings', to='safe_admin.users')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_drop_bookings', to='safe_admin.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.users')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_admin.vehicle')),
            ],
        ),
    ]
