# Generated by Django 5.2.4 on 2025-07-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dropoff_location',
            new_name='dropoff_location_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_location',
            new_name='pickup_location_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='safe_admin.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='safe_admin.vehicle'),
            preserve_default=False,
        ),
    ]
