# Generated by Django 5.2.4 on 2025-07-29 09:39

import safe_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_admin', '0002_rename_dropoff_location_booking_dropoff_location_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='neg_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='user_addhar_image',
            field=models.ImageField(blank=True, null=True, upload_to=safe_admin.models.user_addhar_image_upload_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_dl_image',
            field=models.ImageField(blank=True, null=True, upload_to=safe_admin.models.user_dl_image_upload_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_gender',
            field=models.CharField(max_length=20),
        ),
    ]
