# Generated by Django 5.2.4 on 2025-07-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_admin', '0003_booking_neg_price_alter_users_user_addhar_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='neg_price',
            new_name='user_price',
        ),
    ]
