# Generated by Django 5.2.4 on 2025-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_admin', '0004_rename_neg_price_booking_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
