# Generated by Django 5.2.4 on 2025-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_admin', '0005_staff_full_name_alter_booking_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_eddit_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
