# Generated by Django 5.2.4 on 2025-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_admin', '0006_vehicle_last_eddit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_edited_by_book_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_edited_by_book_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
